# Language System (lang_en, lang_es)
language: lang_es

# SPAWN SETTINGS
spawn:
  worldName: Lobby
  x: 85.0
  y: 129.0
  z: 85.0
  yaw: -91.07189
  pitch: -1.6496022

# CHAT FORMAT SETTINGS
chat:
  # PLACEHOLDERS
  # {message} - Message of the player
  # {displayname} - Display name of the player
  # {prefix} - Prefix of the sender
  # {suffix} - Suffix of the sender
  # {group} - Group name of the sender

  format: '&7{prefix} {displayname}&r&7{suffix}: &7{message}'
  # format: '&f{displayname}&7: &7{message}'
  # format: '&7[{group}]&r {displayname}&7: &7{message}'