# Language System (lang_en, lang_es)
language: lang_es

# SPAWN SETTINGS
spawn:
  worldName: Lobby
  x: 85.0
  y: 129.0
  z: 85.0
  yaw: -91.07189
  pitch: -1.6496022

# CHAT FORMAT SETTINGS
chat-format: '&7[%rank% %player% %suffix% &7]&f%message%'